[package]
name = "arch_aarch64_rpi"
version = "0.1.0"
edition.workspace = true
license.workspace = true
build = "build.rs"

[[bin]]
name = "arch_aarch64_rpi"
path = "src/main.rs"

[dependencies]
kernel = { path = "../kernel" }
hal = { path = "../hal" }


